Fix to support compatability with SQLAlchemy>=1.2.0
LocusEnergy/sqlalchemy-vertica-python pull request #13
Opened 2018-03-26 23:05 UTC by jeffreythewang

This is intended as a temporary fix to fulfill the interface described [here](http://docs.sqlalchemy.org/en/latest/core/reflection.html#sqlalchemy.engine.reflection.Inspector.get_table_comment) for versions of SQLAlchemy >= 1.2.0.

@lemeryfertitta

2018-03-26 23:25 UTC, lemeryfertitta requested changes

2018-03-26 23:25 UTC, lemeryfertitta commented on sqla_vertica_python/vertica_python.py
> +        raise NotImplementedError
@jeffreythewang from my understanding, Vertica supports table comments. Do you have access to a Vertica database? I believe that implementing this method should be relatively easy if you have a database to test against.

2018-03-27 17:22 UTC, jeffreythewang commented
I tested this against Vertica 9 in a [docker-vertica](https://github.com/sumitchawla/docker-vertica) container.

2018-03-27 17:34 UTC, lemeryfertitta commented
Thanks @jeffreythewang! This looks good to me. I'll package it up into a 0.2.2 release

2018-03-27 17:34 UTC, lemeryfertitta approved these changes

2018-03-27 17:35 UTC, merged