Implement is_disconnect
LocusEnergy/sqlalchemy-vertica-python pull request #26
Opened 2018-10-17 03:14 UTC by Lordshinjo

This allows detecting that a disconnect occurred when using pool_pre_ping

2018-10-17 18:31 UTC, lemeryfertitta requested changes
Thanks for the PR! I think its good to be implementing this method, and I'd love to release it after we come up with an implementation that we both feel confident is correct.

2018-10-17 18:31 UTC, lemeryfertitta commented on sqla_vertica_python/vertica_python.py
> +                connection = connection.connection
I'm a bit confused by this line. `connection` is the underlying `__connection` object as far as I know. There should be no `connection.connection`.

I'm also generally unsure that this implementation is correct. From my understanding, we should just be checking the error object for text like `is closed`, e.g. https://github.com/vertica/vertica-python/blob/master/vertica_python/vertica/connection.py#L247

From [the SQLAlchemy docs](https://docs.sqlalchemy.org/en/latest/core/pooling.html#more-on-invalidation):

> all SQLAlchemy dialects include a system called is_disconnect() which will examine the contents of an exception object, including the string message and any potential error codes included with it, in order to determine if this exception indicates that the connection is no longer usable

2018-10-18 04:26 UTC, Lordshinjo commented on sqla_vertica_python/vertica_python.py
> +                connection = connection.connection
You're right about the `connection.connection`. I was looking at the implementation in `pygresql` and got confused.

About checking the error, what I'm getting in my tests is the following, which doesn't have a message at all: https://github.com/vertica/vertica-python/blob/master/vertica_python/vertica/connection.py#L458
It seems that all exceptions we care about raised in `Connection` either are caused by the connection being closed, happen before the connection is opened, or are immediately preceded by a socket close.

2018-10-18 04:33 UTC, lemeryfertitta approved these changes

2018-10-18 04:34 UTC, lemeryfertitta commented on sqla_vertica_python/vertica_python.py
> +                connection = connection.connection
Sounds good, thanks for the explanation. Made some slight syntactical adjustments. I'll release this tomorrow under the next minor version

2018-10-18 04:34 UTC, merged